imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    languages:  ['fr', 'en']
    payment:
        currency: EUR
        decimal: true
    app.path.product_images: /images/products


framework:
    #esi: ~
    translator: { fallbacks: ['en','fr'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
      engines: ['twig']



# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes: ['bootstrap_4_layout.html.twig']


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:     '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Boutique\UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
            form:
                type: Boutique\UserBundle\Form\RegistrationType
                # if you are using Symfony < 2.8 you should use the type name instead
                # type: app_user_registration
    profile:
            form:
                type: Boutique\UserBundle\Form\ProfileFormType


vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/web/images/products'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        product_images:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/web/images/products'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true

# app/config/config.yml
easy_admin:
    site_name: "myShopper"
    list:
        actions: ['show','edit', 'search', '-delete']
    design:
        brand_color: '#FFD700'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Produits:
            class: Boutique\ProduitsBundle\Entity\Product
            list:
                sort: ['nom', 'ASC']
                fields:
                    - { property: 'nom', label: 'désignation' }
                    - { property: 'photoPrincipale.imageName', type: 'image', label: 'image' , base_path: '%app.path.product_images%'}
                    - { property: 'categorys', type: 'array',label: 'catégorie' }
                    - { property: 'prix', label: 'prix unitaire' }
                    - { property: 'quantite', label: 'stock' }
    #                - { property: 'description', label: 'description' }
            show:
                fields:
                    - { property: 'nom', label: 'désignation' }
                    - { property: 'photoPrincipale.imageName', type: 'image', base_path: '%app.path.product_images%', label: 'image'}
                    - { property: 'categorys', label: 'catégorie' }
                    - { property: 'prix', label: 'prix' }
                    - { property: 'quantite', label: 'stock' }
                    - { property: 'images', label: 'images'}
            form:
                fields:
                    - { property: 'nom', label: 'désignation' }
                    - { property: 'description', label: 'description' }
                    - { property: 'categorys', label: 'catégorie' }
                    - { property: 'prix', label: 'prix' }
                    - { property: 'quantite', label: 'stock' }
            new:
                fields:
                    - { property: 'nom', label: 'désignation' }
                    - { property: 'photoPrincipale', type: 'Boutique\ProduitsBundle\Form\PhotoPrincipaleType', base_path: '%app.path.product_images%'}
                    - { property: 'categorys', label: 'catégorie' }
                    - { property: 'prix', label: 'prix unitaire' }
                    - { property: 'quantite', label: 'stock' }
                    - { property: 'image'}
        Categories:
            class: Boutique\ProduitsBundle\Entity\Category
            list:
                sort: ['nom', 'ASC']
                fields:
                - { property: 'nom', label: 'titre français' }
                - { property: 'trad', label: 'titre anglais' }
                - { property: 'description', label: 'description' }
            show:
                fields:
                - { property: 'nom', label: 'titre français' }
                - { property: 'trad', label: 'titre anglais' }
                - { property: 'description', label: 'description' }
            form:
                fields:
                    - { property: 'nom', label: 'titre en français' }
                    - { property: 'trad', label: 'titre en anglais' }
                    - { property: 'description', label: 'description' }
            new:
                - { property: 'nom', label: 'titre en français' }
                - { property: 'trad', label: 'titre en anglais' }
                - { property: 'description', label: 'description' }

        Utilisateurs:
            class: Boutique\UserBundle\Entity\User
        Photos:
            class: Boutique\ProduitsBundle\Entity\PhotoPrincipale
            list:
                fields:
                - { property: 'imageName', type: 'image', base_path: '%app.path.product_images%' }
                - { property: 'alt', label: 'texte alternatif'}
                - { property: 'updated_at', label: 'modifié le', type: datetime }
            show:
                fields:
                - { property: 'imageName', label: 'titre français' }
                - { property: 'alt', label: 'texte alternatif' }
                - { property: 'updated_at', label: 'modifié le', type: datetime }