boutique_front:
    resource: "@BoutiqueFrontBundle/Controller/"
    type:     annotation
    prefix:   /

boutique_produits:
    resource: "@BoutiqueProduitsBundle/Controller/"
    type:     annotation
    prefix:   /boutique

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

produits:
    type: rest
    resource: Boutique\ProduitsBundle\Controller\ProductController

categories:
    type: rest
    resource: Boutique\ProduitsBundle\Controller\CategoryRestController