boutique_front:
    resource: "@BoutiqueFrontBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en

boutique_produits:
    resource: "@BoutiqueProduitsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/boutique
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}

produits:
    type: rest
    resource: Boutique\ProduitsBundle\Controller\ProductController

categories:
    type: rest
    resource: Boutique\ProduitsBundle\Controller\CategoryRestController

