<?php

namespace Boutique\ProduitsBundle\Repository;

/**
 * PhotoPrincipaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoPrincipaleRepository extends \Doctrine\ORM\EntityRepository
{
}
