<?php

namespace Boutique\ProduitsBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNameLike($terme){
        $query = $this->createQueryBuilder('p')
            ->where("p.nomProduit LIKE :terme")
            ->setParameter('terme','%'.$terme.'%')
            ->getQuery();
        return $query->execute();
    }
}
