<?php

namespace Boutique\ProduitsBundle\Repository;


use Boutique\ProduitsBundle\Entity\Category;
use Boutique\ProduitsBundle\Entity\Product;
use Doctrine\ORM\Query\Expr\Join;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNameLike($terme){
        $query = $this->createQueryBuilder('p')
            ->where("p.nomProduit LIKE :terme")
            ->setParameter('terme','%'.$terme.'%')
            ->getQuery();
        return $query->execute();
    }



    public function findByCategory($c){
        return $this->createQueryBuilder('p')
            ->join('p.categorys', 'c')
            ->where(' c.id = :id ')
            ->setParameter('id', $c)
            ->getQuery()
            ->getResult();
    }

    public function pricesBetween($min, $max){
        return $this->createQueryBuilder('p')
            ->where('p.prix BETWEEN :min AND :max')
            ->setParameter('min', $min)
            ->setParameter('max', $max)
            ->getQuery()
            ->getResult();
    }
}
